blank_issues_enabled: true
contact_links:
  - name: Question / Discussion
    url: https://github.com/j1s4nn/ARIA-Adaptive-Resilient-Intelligent-Autopilot-For-Drone/discussions
    about: Ask questions and discuss ideas with the community.
